import express from "express";
import getBuses from "./getBuses.js";
import checkBasic from "./check.js";
import getStop from "./getStops.js";
import getBus from "./getBus.js";
import getBusByNo from "./getBusByRouteNumber.js";
import getOnlineBuses from "./getOnlineBuses.js";
const basicRouter = express.Router();
basicRouter.get("/get/bus",getBuses);
basicRouter.get("/",checkBasic);
basicRouter.get("/get/stop",getStop);
basicRouter.get("/get/bus/:number_plate",getBus);
basicRouter.get("/get/onlinebus",getOnlineBuses);
basicRouter.get("/get/busbyno/:route_number",getBusByNo);
export default basicRouter;