import express from "express";
import sendOtp from "./sendOtp.js";
import verifyOtp from "./verifyOtp.js";
import linkDriver from "./linkDriver.js";
import setOnlineTrue from "./setOnlineTrue.js";
import setOnlineFalse from "./setOnlineFalse.js";
const driverRouter = express.Router();
driverRouter.post("/sendotp",sendOtp);
driverRouter.post("/verifyotp",verifyOtp);
driverRouter.post("/linkdriver",linkDriver);
driverRouter.post("/setonline",setOnlineTrue);
driverRouter.post("/setoffline",setOnlineFalse);
export default driverRouter;